Alpha diversity

```{r}
getwd()
```

```{r message=FALSE, warning=FALSE}
library(ape)
library(vegan)
library(plyr)
library(dplyr)
library(scales)
library(grid)
library(reshape2)
library(phyloseq)
library(magrittr)
library(ggplot2)
library(ggpubr)
library(data.table)
library(tidyr)
library(tidyverse)
library(multcompView)
library(car)
```

```{r}
meta = read.table("D:/PP/4/senior project/Data/CrustTemp216SasvUN3.mapping_file_fix.txt",header=TRUE,row.names=1,sep="\t",stringsAsFactors=FALSE)
```

```{r warning=FALSE}
head(meta)
```

```{r}
sampleData <- sample_data(meta)
```

```{r}
otus <- read.table("D:/PP/4/senior project/Data/CrustTemp216SasvUN3.asv_table.fix.txt",header=T,sep="\t",row.names=1)
otumat <- as(as.matrix(otus), "matrix")
OTU = otu_table(otumat, taxa_are_rows = TRUE)
```

```{r}
taxmat <- read.table("D:/PP/4/senior project/Data/CrustTemp216SasvUN3.taxonomy_file_fix.txt", header=T,sep="\t",row.names=1)
taxmat <- as(as.matrix(taxmat),"matrix")
TAX = tax_table(taxmat)
```

```{r warning=FALSE}
physeq = phyloseq(OTU,TAX,sampleData)
```

```{r warning=FALSE}
physeq
```

```{r}
physeq <- subset_taxa(physeq, Kingdom == "Bacteria")
physeq
```

```{r }
physeq.prune = prune_taxa(taxa_sums(physeq) > 1, physeq)
physeq.prune
```

```{r}
physeq.LAC = subset_samples(physeq.prune, Crusttype=="LAC")
```

```{r}
sample_data(physeq.LAC)$Incubation = factor(sample_data(physeq.LAC)$Incubation, levels = c("0.05", "1", "24", "48", "96"))
```

```{r}
alpha.diversity.LAC = estimate_richness(physeq.LAC, measures = c("Observed"))
data.anova.LAC = cbind(sample_data(physeq.LAC), alpha.diversity.LAC)
physeq.anova.LAC = aov(Observed ~ Incubation, data.anova.LAC)
summary(physeq.anova.LAC)

```

```{r}
tukey.ps.LAC = TukeyHSD(x=physeq.anova.LAC, 'Incubation', conf.level = 0.95)

generate_label_df.LAC <- function(tukey.ps.LAC, variable){
 
     # Extract labels and factor levels from Tukey post-hoc 
     Tukey.levels.LAC <- tukey.ps.LAC[[variable]][,4]
     Tukey.labels.LAC <- data.frame(multcompLetters(Tukey.levels.LAC)['Letters'])
     
     #I need to put the labels in the same order as in the boxplot :
     Tukey.labels.LAC$treatment=rownames(Tukey.labels)
     Tukey.labels.LAC=Tukey.labels.LAC[order(Tukey.labels.LAC$treatment) , ]
     return(Tukey.labels.LAC)
     }

LABELS.LAC=generate_label_df(tukey.ps.LAC, 'Incubation')
names(LABELS.LAC) = c('Letters','Incubation')
```

```{r}
LABELS.LAC
```

```{r}
ylabel.LAC <- data.frame("ylabel.LAC" = c(3500, 3500, 3500, 3200, 3000)) #LAC surface
#ylabel <- data.frame("ylabel" = c(340, 400, 340, 380, 290,  460, 510, 590, 460, 270, 230, 350)) #CLC surface

```


```{r}
LABELS.LAC$ylabel.LAC<-ylabel.LAC$ylabel.LAC
```

```{r}
physeq.plot.richness.incubation.LAC = plot_richness(physeq.LAC, x="Incubation", color=("Incubation"), measures=c("Observed")) + 
  geom_boxplot(lwd=0.5) + ggtitle("LAC Bacterial Alpha Diversity by Incubation time") + 
  stat_compare_means(method = "anova", label.y = 3700, label.x = 4.5) + 
  theme_pubr(border= TRUE, legend = c("none")) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_colour_hue(l = 58) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_text(data=LABELS.LAC, aes(x=LABELS.LAC$Incubation, y = LABELS.LAC$ylabel , label = LABELS.LAC$Letters))

physeq.plot.richness.incubation.LAC
```

```{r}
png("./Figures/1LAC_Bacterial_Alpha_Div_Incubation_time.png", units="in", width = 6, height = 4, res = 600 )
physeq.plot.richness.incubation.LAC
dev.off()
``` 
#Alpha diversity of CLC

```{r}
physeq.CLC = subset_samples(physeq.prune, Crusttype=="CLC")
```
```{r}
#sample_data(physeq.LAC)$Incubation = factor(sample_data(physeq.LAC)$Incubation, levels = c("0.05", "1", "24", "48", "96"))

sample_data(physeq.CLC)$Incubation = factor(sample_data(physeq.CLC)$Incubation, levels = c("0.05", "1", "24", "48", "96"))
```

```{r}
alpha.diversity = estimate_richness(physeq.CLC, measures = c("Observed"))
data.anova = cbind(sample_data(physeq.CLC), alpha.diversity)
physeq.anova = aov(Observed ~ Incubation, data.anova)
summary(physeq.anova)
```
```{r}
tukey.ps = TukeyHSD(x=physeq.anova, 'Incubation', conf.level = 0.95)

generate_label_df <- function(tukey.ps, variable){
 
     # Extract labels and factor levels from Tukey post-hoc 
     Tukey.levels <- tukey.ps[[variable]][,4]
     Tukey.labels <- data.frame(multcompLetters(Tukey.levels)['Letters'])
     
     #I need to put the labels in the same order as in the boxplot :
     Tukey.labels$treatment=rownames(Tukey.labels)
     Tukey.labels=Tukey.labels[order(Tukey.labels$treatment) , ]
     return(Tukey.labels)
     }

LABELS=generate_label_df(tukey.ps, 'Incubation')
names(LABELS) = c('Letters','Incubation')
```

```{r}
LABELS
```

```{r}
ylabel <- data.frame("ylabel" = c(3200, 2700, 3200, 2800, 2500)) #LAC surface
#ylabel <- data.frame("ylabel" = c(340, 400, 340, 380, 290,  460, 510, 590, 460, 270, 230, 350)) #CLC surface
```


```{r}
LABELS$ylabel<-ylabel$ylabel
```

```{r}
physeq.plot.richness.incubation = plot_richness(physeq.CLC, x="Incubation", color=("Incubation"), measures=c("Observed")) + 
  geom_boxplot(lwd=0.5) + ggtitle("CLC Bacterial Alpha Diversity by Incubation time") + 
  stat_compare_means(method = "anova", label.y = 3300, label.x = 4.5) + 
  theme_pubr(border= TRUE, legend = c("none")) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_colour_hue(l = 58) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_text(data=LABELS, aes(x=LABELS$Incubation, y = LABELS$ylabel , label = LABELS$Letters))
physeq.plot.richness.incubation
```
```{r warning=FALSE}
png("./Figures/1CLC_Bacterial_Alpha_Div_Incubation_time.png", units="in", width = 6, height = 4, res = 600 )
physeq.plot.richness.incubation
dev.off()
```